CLOUD-715 improve upgrade doc
percona/k8spxc-docs pull request #10
Opened 2022-11-15 07:22 UTC by fiowro

2022-12-05 12:25 UTC, cap1984 commented on docs/update.md
> +    $ helm upgrade my-op percona/pxc-operator helm upgrade --version {{ release }}
helm upgrade two times?

2022-12-05 12:25 UTC, cap1984 commented on docs/update.md
> +    $ helm upgrade my-op percona/pxc-operator helm upgrade --version {{ release }} -f my-values.yaml
the same

2022-12-06 16:08 UTC, tplavcic requested changes

2022-12-06 20:31 UTC, fiowro commented on docs/update.md
> +issues until the whole cluster is updated to the new settings.
Ok! Added this text to the note about the "apply" option

2022-12-07 13:48 UTC, tplavcic approved these changes

2022-12-07 16:34 UTC, merged