K8SPXC-1407 Clarify HA Proxy upgrade risks
percona/k8spxc-docs pull request #153
Opened 2024-06-13 22:00 UTC by fiowro

2024-06-14 08:30 UTC, hors requested changes

2024-06-14 08:30 UTC, hors commented on docs/update.md
> +        * If you are using [custom configuration for HA Proxy](haproxy-conf.md#passing-custom-configuration-options-to-haproxy), check [HA Proxy release information](https://www.haproxy.org/) to make
@fiowro, the issue is that we occasionally add new options to the HAProxy configuration. If users are using a custom configuration for HAProxy, they need to check the default configuration at https://github.com/percona/percona-docker/blob/pxc-operator-1.14.0/haproxy/dockerdir/etc/haproxy/haproxy-global.cfg and incorporate any new options into their custom config.

For example, in this commit: https://github.com/percona/percona-docker/commit/f2b9f63e8c288d219522ea76ae6b113e2717a59c, we added two new options in different places. If these options are not included in the custom config, users may experience downtime.

The instructions are as follows:
1. check new conf before the update
2. add new options while the update into CR

2024-06-19 10:09 UTC, egegunes requested changes

2024-06-19 10:09 UTC, egegunes commented on docs/update.md
> +        The above command upgrades various components of the cluster including PMM Client. If you didn't follow the [official recommendation](https://docs.percona.com/percona-monitoring-and-managemen
```suggestion
        The above command upgrades various components of the cluster including PMM Client. If you didn't follow the [official recommendation](https://docs.percona.com/percona-monitoring-and-management/how-to/upgrade.html) to upgrade PMM Server before upgrading PMM Client, you can avoid PMM Client upgrade by removing it from the list of images as follows:
```

2024-06-19 10:09 UTC, egegunes commented on docs/update.md
> +        **before upgrading**, check the HA Proxy configuration file provided by
```suggestion
        **before upgrading**, check the HAProxy configuration file provided by
```

2024-06-19 10:09 UTC, egegunes commented on docs/update.md
> +    * If you are using [custom configuration for HA Proxy](haproxy-conf.md#passing-custom-configuration-options-to-haproxy),
```suggestion
    * If you are using [custom configuration for HAProxy](haproxy-conf.md#passing-custom-configuration-options-to-haproxy), 
```

2024-06-19 10:09 UTC, egegunes commented on docs/haproxy-conf.md
> +    [HA Proxy configuration file](https://github.com/percona/percona-docker/blob/pxc-operator-{{ release }}/haproxy/dockerdir/etc/haproxy/haproxy-global.cfg)
```suggestion
    [HAProxy configuration file](https://github.com/percona/percona-docker/blob/pxc-operator-{{ release }}/haproxy/dockerdir/etc/haproxy/haproxy-global.cfg)
```

2024-06-19 10:09 UTC, egegunes commented on docs/update.md
> +    *  It is [highly recommended](https://docs.percona.com/percona-monitoring-and-management/how-to/upgrade.html)
```suggestion
    *  It is **highly recommended**
```

2024-06-19 10:09 UTC, egegunes commented on docs/update.md
> +        to upgrade PMM Server **before** upgrading PMM Client.
```suggestion
        to [upgrade PMM Server](https://docs.percona.com/percona-monitoring-and-management/how-to/upgrade.html) **before** upgrading PMM Client.
```

2024-06-19 10:54 UTC, egegunes approved these changes

2024-06-19 10:55 UTC, merged