CLOUD-715 add crVersion update
percona/k8spxc-docs pull request #30
Opened 2022-12-15 12:01 UTC by fiowro

2022-12-15 13:09 UTC, tplavcic approved these changes

2022-12-15 13:12 UTC, tplavcic requested changes
As discussed it seems it would be more appropriate that crVersion is part of DB upgrade steps then operator upgrade steps.

2022-12-16 09:44 UTC, spron-in commented on docs/update.md
> +2. Set the `upgradeOptions.apply` option to one of the following values:
Also it might be cool to explain how to trigger the upgrade right away. Change the schedule to `* * * * *` ?

2022-12-16 09:45 UTC, spron-in commented on docs/update.md
> +    * `Never` or `Disabled` - disable automatic upgrades (the default choice
remember, that this is the default

2022-12-27 07:32 UTC, spron-in commented on docs/update.md
> +    [appropriate section](update.md#more-on-upgrade-strategies).
```suggestion
    As an alternative, the `updateStrategy` key can be set to `RollingUpdate` 
    and `OnDelete`. You can find out more about it in the
    [appropriate section](update.md#more-on-upgrade-strategies).
```

2022-12-27 11:59 UTC, tplavcic approved these changes

2023-01-26 08:31 UTC, merged