K8SPXC-1192 improve backup documentation
percona/k8spxc-docs pull request #37
Opened 2023-01-23 14:21 UTC by hors

* add descriptions for restore options
    * add links to backup secrets

2023-01-24 06:28 UTC, spron-in commented on docs/backups.md
The doc starts with two similar sentences:

The Operator usually stores Percona XtraDB Cluster backups on [Amazon S3 or S3-compatible
storage](https://en.wikipedia.org/wiki/Amazon_S3#S3_API_and_competing_services) outside the Kubernetes cluster:
The Operator usually stores Percona XtraDB Cluster backups outside the
Kubernetes cluster, on [Amazon S3 or S3-compatible storage](https://en.wikipedia.org/wiki/Amazon_S3#S3_API_and_competing_services),
or on [Azure Blob Storage](https://azure.microsoft.com/en-us/services/storage/blobs/):

why is that?

2023-01-27 12:02 UTC, tplavcic requested changes

2023-01-27 12:02 UTC, tplavcic commented on docs/operator.md
> +configuration file. This Custrom Resource contains the following options:
`Custrom` -> `Custom`

2023-01-27 12:10 UTC, tplavcic approved these changes

2023-01-31 18:59 UTC, fiowro approved these changes

2023-01-31 19:00 UTC, merged